<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Abacus.png', array('width'=>'24','height'=>'24','alt' =>'Abacus'))?><span>Abacus</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Acces Denied Sign.png', array('width'=>'24','height'=>'24','alt' =>'Acces Denied Sign'))?><span>Acces Denied Sign</span></span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Address Book.png', array('width'=>'24','height'=>'24','alt' =>'Address Book'))?><span>Address Book</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Admin User 2.png', array('width'=>'24','height'=>'24','alt' =>'Admin User 2'))?><span>Admin User 2</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Admin User.png', array('width'=>'24','height'=>'24','alt' =>'Admin User'))?><span>Admin User</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Airplane.png', array('width'=>'24','height'=>'24','alt' =>'Airplane'))?><span>Airplane</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/alarm bell 2.png', array('width'=>'24','height'=>'24','alt' =>'alarm bell 2'))?><span>alarm bell 2</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/alarm bell.png', array('width'=>'24','height'=>'24','alt' =>'alarm bell'))?><span>alarm bell</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Alarm Clock.png', array('width'=>'24','height'=>'24','alt' =>'Alarm Clock'))?><span>Alarm Clock</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Alert 2.png', array('width'=>'24','height'=>'24','alt' =>'Alert 2'))?><span>Alert 2</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Alert.png', array('width'=>'24','height'=>'24','alt' =>'Alert'))?><span>Alert</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Android.png', array('width'=>'24','height'=>'24','alt' =>'Android'))?><span>Android</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Apartment Building.png', array('width'=>'24','height'=>'24','alt' =>'Apartment Building'))?><span>Apartment Building</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Archive.png', array('width'=>'24','height'=>'24','alt' =>'Archive'))?><span>Archive</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Bag.png', array('width'=>'24','height'=>'24','alt' =>'Bag'))?><span>Bag</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Balloons.png', array('width'=>'24','height'=>'24','alt' =>'Balloons'))?><span>Balloons</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Bandaid.png', array('width'=>'24','height'=>'24','alt' =>'Bandaid'))?><span>Bandaid</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Battery Almost Empty.png', array('width'=>'24','height'=>'24','alt' =>'Battery Almost Empty'))?><span>Battery Almost Empty</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Battery Almost Full.png', array('width'=>'24','height'=>'24','alt' =>'Battery Almost Full'))?><span>Battery Almost Full</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Battery Empty.png', array('width'=>'24','height'=>'24','alt' =>'Battery Empty'))?><span>Battery Empty</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Battery Full.png', array('width'=>'24','height'=>'24','alt' =>'Battery Full'))?><span>Battery Full</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Battery.png', array('width'=>'24','height'=>'24','alt' =>'Battery'))?><span>Battery</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Bended Arrow Down.png', array('width'=>'24','height'=>'24','alt' =>'Bended Arrow Down'))?><span>Bended Arrow Down</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Bended Arrow Left.png', array('width'=>'24','height'=>'24','alt' =>'Bended Arrow Left'))?><span>Bended Arrow Left</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Bended Arrow Right.png', array('width'=>'24','height'=>'24','alt' =>'Bended Arrow Right'))?><span>Bended Arrow Right</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Bended Arrow Up.png', array('width'=>'24','height'=>'24','alt' =>'Bended Arrow Up'))?><span>Bended Arrow Up</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Big Brush.png', array('width'=>'24','height'=>'24','alt' =>'Big Brush'))?><span>Big Brush</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Blackberry.png', array('width'=>'24','height'=>'24','alt' =>'Blackberry'))?><span>Blackberry</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/blocks images.png', array('width'=>'24','height'=>'24','alt' =>'blocks images'))?><span>blocks images</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Blu-ray.png', array('width'=>'24','height'=>'24','alt' =>'Blu-ray'))?><span>Blu-ray</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/bluetooth 2.png', array('width'=>'24','height'=>'24','alt' =>'skin_colour bluetooth 2'))?><span>bluetooth 2</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/bluetooth.png', array('width'=>'24','height'=>'24','alt' =>'skin_colour bluetooth'))?><span>bluetooth</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Book Large.png', array('width'=>'24','height'=>'24','alt' =>'Book Large'))?><span>Book Large</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Book.png', array('width'=>'24','height'=>'24','alt' =>'Book'))?><span>Book</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Books.png', array('width'=>'24','height'=>'24','alt' =>'Books'))?><span>Books</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Box Incoming.png', array('width'=>'24','height'=>'24','alt' =>'Box Incoming'))?><span>Box Incoming</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Box Outgoing.png', array('width'=>'24','height'=>'24','alt' =>'Box Outgoing'))?><span>Box Outgoing</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Bulls Eye.png', array('width'=>'24','height'=>'24','alt' =>'Bulls Eye'))?><span>Bulls Eye</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Calculator.png', array('width'=>'24','height'=>'24','alt' =>'Calculator'))?><span>Calculator</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Camera 2.png', array('width'=>'24','height'=>'24','alt' =>'Camera 2'))?><span>Camera 2</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Camera.png', array('width'=>'24','height'=>'24','alt' =>'Camera'))?><span>Camera</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Car.png', array('width'=>'24','height'=>'24','alt' =>'Car'))?><span>Car</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Cash Register.png', array('width'=>'24','height'=>'24','alt' =>'Cash Register'))?><span>Cash Register</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Cassette.png', array('width'=>'24','height'=>'24','alt' =>'Cassette'))?><span>Cassette</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Cat.png', array('width'=>'24','height'=>'24','alt' =>'Cat'))?><span>Cat</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/CD.png', array('width'=>'24','height'=>'24','alt' =>'CD'))?><span>CD</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Chair.png', array('width'=>'24','height'=>'24','alt' =>'Chair'))?><span>Chair</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Chart 2.png', array('width'=>'24','height'=>'24','alt' =>'Chart 2'))?><span>Chart 2</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Chart 3.png', array('width'=>'24','height'=>'24','alt' =>'Chart 3'))?><span>Chart 3</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Chart 4.png', array('width'=>'24','height'=>'24','alt' =>'Chart 4'))?><span>Chart 4</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Chart 5.png', array('width'=>'24','height'=>'24','alt' =>'Chart 5'))?><span>Chart 5</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Chart 6.png', array('width'=>'24','height'=>'24','alt' =>'Chart 6'))?><span>Chart 6</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Chart 7.png', array('width'=>'24','height'=>'24','alt' =>'Chart 7'))?><span>Chart 7</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Chart 8.png', array('width'=>'24','height'=>'24','alt' =>'Chart 8'))?><span>Chart 8</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Chart.png', array('width'=>'24','height'=>'24','alt' =>'Chart'))?><span>Chart</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Chemical.png', array('width'=>'24','height'=>'24','alt' =>'Chemical'))?><span>Chemical</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Chrome.png', array('width'=>'24','height'=>'24','alt' =>'Chrome'))?><span>Chrome</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Clipboard.png', array('width'=>'24','height'=>'24','alt' =>'Clipboard'))?><span>Clipboard</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Clock.png', array('width'=>'24','height'=>'24','alt' =>'Clock'))?><span>Clock</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Cloud Download.png', array('width'=>'24','height'=>'24','alt' =>'Cloud Download'))?><span>Cloud Download</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Cloud Upload.png', array('width'=>'24','height'=>'24','alt' =>'Cloud Upload'))?><span>Cloud Upload</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Cloud.png', array('width'=>'24','height'=>'24','alt' =>'Cloud'))?><span>Cloud</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Cog 2.png', array('width'=>'24','height'=>'24','alt' =>'Cog 2'))?><span>Cog 2</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Cog 3.png', array('width'=>'24','height'=>'24','alt' =>'Cog 3'))?><span>Cog 3</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Cog 4.png', array('width'=>'24','height'=>'24','alt' =>'Cog 4'))?><span>Cog 4</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Cog.png', array('width'=>'24','height'=>'24','alt' =>'Cog'))?><span>Cog</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Companies.png', array('width'=>'24','height'=>'24','alt' =>'Companies'))?><span>Companies</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Computer_iMac.png', array('width'=>'24','height'=>'24','alt' =>'Computer_iMac'))?><span>Computer_iMac</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Coverflow.png', array('width'=>'24','height'=>'24','alt' =>'Coverflow'))?><span>Coverflow</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/create write.png', array('width'=>'24','height'=>'24','alt' =>'create write'))?><span>create write</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Cup.png', array('width'=>'24','height'=>'24','alt' =>'Cup'))?><span>Cup</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/cut scissors.png', array('width'=>'24','height'=>'24','alt' =>'cut scissors'))?><span>cut scissors</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Day Calendar.png', array('width'=>'24','height'=>'24','alt' =>'Day Calendar'))?><span>Day Calendar</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Delicious.png', array('width'=>'24','height'=>'24','alt' =>'Delicious'))?><span>Delicious</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Digg 2.png', array('width'=>'24','height'=>'24','alt' =>'Digg 2'))?><span>Digg 2</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Digg.png', array('width'=>'24','height'=>'24','alt' =>'Digg'))?><span>Digg</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Document.png', array('width'=>'24','height'=>'24','alt' =>'Document'))?><span>Document</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Documents.png', array('width'=>'24','height'=>'24','alt' =>'Documents'))?><span>Documents</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Download To Computer.png', array('width'=>'24','height'=>'24','alt' =>'Download To Computer'))?><span>Download To Computer</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Download.png', array('width'=>'24','height'=>'24','alt' =>'Download'))?><span>Download</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Dress.png', array('width'=>'24','height'=>'24','alt' =>'Dress'))?><span>Dress</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Dribbble 2.png', array('width'=>'24','height'=>'24','alt' =>'Dribbble 2'))?><span>Dribbble 2</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Dribbble.png', array('width'=>'24','height'=>'24','alt' =>'Dribbble'))?><span>Dribbble</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Dropbox.png', array('width'=>'24','height'=>'24','alt' =>'Dropbox'))?><span>Dropbox</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Drupal.png', array('width'=>'24','height'=>'24','alt' =>'Drupal'))?><span>Drupal</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/DVD.png', array('width'=>'24','height'=>'24','alt' =>'DVD'))?><span>DVD</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Electricity Input.png', array('width'=>'24','height'=>'24','alt' =>'Electricity Input'))?><span>Electricity Input</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Electricity Plug.png', array('width'=>'24','height'=>'24','alt' =>'Electricity Plug'))?><span>Electricity Plug</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Excel Document.png', array('width'=>'24','height'=>'24','alt' =>'Excel Document'))?><span>Excel Document</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Excel Documents.png', array('width'=>'24','height'=>'24','alt' =>'Excel Documents'))?><span>Excel Documents</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Exit.png', array('width'=>'24','height'=>'24','alt' =>'Exit'))?><span>Exit</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Exposé.png', array('width'=>'24','height'=>'24','alt' =>'Exposé'))?><span>Exposé</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Expression Engine.png', array('width'=>'24','height'=>'24','alt' =>'Expression Engine'))?><span>Expression Engine</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Eyedropper.png', array('width'=>'24','height'=>'24','alt' =>'Eyedropper'))?><span>Eyedropper</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Facebook Like.png', array('width'=>'24','height'=>'24','alt' =>'Facebook Like'))?><span>Facebook Like</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Facebook.png', array('width'=>'24','height'=>'24','alt' =>'Facebook'))?><span>Facebook</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Fax.png', array('width'=>'24','height'=>'24','alt' =>'Fax'))?><span>Fax</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Female Contour.png', array('width'=>'24','height'=>'24','alt' =>'Female Contour'))?><span>Female Contour</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Female symbol.png', array('width'=>'24','height'=>'24','alt' =>'Female symbol'))?><span>Female symbol</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/File Cabinet.png', array('width'=>'24','height'=>'24','alt' =>'File Cabinet'))?><span>File Cabinet</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Film Camera.png', array('width'=>'24','height'=>'24','alt' =>'Film Camera'))?><span>Film Camera</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Film Strip 2.png', array('width'=>'24','height'=>'24','alt' =>'Film Strip 2'))?><span>Film Strip 2</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Film Strip.png', array('width'=>'24','height'=>'24','alt' =>'Film Strip'))?><span>Film Strip</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Finish Flag.png', array('width'=>'24','height'=>'24','alt' =>'Finish Flag'))?><span>Finish Flag</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Firefox.png', array('width'=>'24','height'=>'24','alt' =>'Firefox'))?><span>Firefox</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Flag 2.png', array('width'=>'24','height'=>'24','alt' =>'Flag 2'))?><span>Flag 2</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Flag.png', array('width'=>'24','height'=>'24','alt' =>'Flag'))?><span>Flag</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Folder.png', array('width'=>'24','height'=>'24','alt' =>'Folder'))?><span>Folder</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Footprints.png', array('width'=>'24','height'=>'24','alt' =>'Footprints'))?><span>Footprints</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Fountain Pen.png', array('width'=>'24','height'=>'24','alt' =>'Fountain Pen'))?><span>Fountain Pen</span></button>
<button class='skin_colour blue round_all'><?php echo $html->image('admin/icons/small/white/Frames.png', array('width'=>'24','height'=>'24','alt' =>'Frames'))?><span>Frames</span></button>